config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :admin
  resources :stores, except: %i[:delete]
  resources :employees, except: %i[:delete]
  resources :attendances, except: %i[:delete]
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_many :employees, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
  attr_accessor :private_number
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :admin
  belongs_to :store
  has_many   :attendances, dependent: :destroy
  validates  :private_number, presence: true, uniqueness: true
  validates  :email,
             :name,
             :position,
             :store_id,
             presence: true
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :employees, dependent: :destroy
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authorize, except: %i[new create]
  before_action :set_admin, only: %i[show edit update destroy]

  def new; end

  def create
    @admin = Admin.find_by(email: params[:email])
    if @admin.password_digest == params[:password]
      session[:admin_id] = @admin.id
      redirect_to root_path, notice: 'You have successfully signed in'
    else
      flash[:alert] = 'There was a problem with your username or password'
      render :new
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to new_admin_path, notice: 'You have successfully logged out'
  end

  private

  def params_admin
    params.admit(:admin).permit(:email, :password)
  end

  def set_admin
    @admin = Admin.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  protect_from_forgery with: :exception

  def current_admin
    @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
  end

  def authorize
    redirect_to '/admin/new', alert: 'Please Log in to view admin page' unless current_admin
  end
end

app/controllers/attendances_controller.rb
require 'awesome_print'
class AttendancesController < ApplicationController

  def index
    @attendances = Attendance.all
  end

  def show; end

  def new
    @attendance = Attendance.new
  end

  def edit
    employee = Employee.find_by(private_number: attendance_params[:private_number].to_i)
    if employee.nil?
      @attendance = Attendance.find(params[:id])
    else
      attendance = employee.attendances.last
      @attendance = Attendance.find(attendance.id)
    end
  end 

  def create
    employee = Employee.find_by(private_number: attendance_params[:private_number].to_i)

    if !employee.nil?
      ap '*' * 125
      @attendance = Attendance.new
      @attendance.employee_id = employee.id
      @attendance.check_in = Time.now
      @attendance.save
      redirect_to root_path, notice: 'Attendance was successfully created.'   
    elsif employee.nil?
      Attendance.new(attendance_params).save
      ap '!' * 125
      redirect_to root_path, notice: 'Attendance was successfully created.'   
    else
      ap '@' * 125
      redirect_to root_path, status: :unprocessable_entity
    end
  end

  def update
    ap '=======================> update @' * 125
    employee = Employee.find_by(private_number: attendance_params[:private_number].to_i)
    if employee.nil?
      attendance = Attendance.find(params[:id])
    else
      attendance = employee.attendances.last
    end

    return render :root_path, status: :unprocessable_entity unless attendance.update(check_out: Time.now)

    redirect_to root_path, notice: 'Attendance was successfully updated.'
  end

  private

  def attendance_params
    params.permit(:check_in, :check_out, :private_number, :button, :authenticity_token, :commit)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[show edit update destroy]

  def index
    @employees = Employee.all
  end

  def show; end

  def new
    @employee = Employee.new
  end

  def edit; end

  def create
    @employee = Admin.first.employees.new(employee_params)
    return render :new, status: :unprocessable_entity unless @employee.save

    redirect_to employees_path, notice: 'Employee was successfully created.'
  end

  def update
    return render :edit, status: :unprocessable_entity unless @employee.update(employee_params)

    redirect_to employees_path, notice: 'Employee was successfully updated.'
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:email, :name, :position, :private_number, :active, :admin_id, :store_id)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[show edit update destroy]

  def index
    @stores = Store.all
  end

  def show; end

  def new
    @store = Store.new
  end

  def edit; end

  def create
    @store = Store.new(store_params)
    return render :new, status: :unprocessable_entity unless @store.save

    redirect_to @store, notice: 'Store was successfully created.'
  end

  def update
    return render :edit, status: :unprocessable_entity unless @store.update(store_params)

    redirect_to @store, notice: 'Store was successfully updated.'
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :address)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authorize, except: [:index]
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def stores_for_select
    Store.all.map { |store| [store.name, store.id] }
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/new.html.erb
<h1>Login</h1> 
<%= form_tag('/admin') do %>
  <div class="mb-3">
    <p> 
    <%= label_tag :email, nil, class: "form-label"%> 
    <%= text_field_tag :email, nil, class: "form-control" %> 
    </p> 
  </div>
  <div class="mb-3">
    <p> 
    <%= label_tag :password, nil, class: "form-label" %> 
    <%= password_field_tag :password, nil, class: "form-control" %> 
    </p>
  </div>
  <div class="mb-3">
    <%= submit_tag 'Log in', class: "btn btn-primary"%>
    </p>
  </div>
<% end %>

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.datetime_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.datetime_select :check_out %>
  </div>

  <div class="field">
    <%= form.label :private_number %>
    <%= form.text_field :private_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendances</h1>

<table>
  <thead>
    <tr>
      <th>Check in</th>
      <th>Check out</th>
      <th>Employee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendances.each do |attendance| %>
      <tr>
        <td><%= attendance.check_in %></td>
        <td><%= attendance.check_out %></td>
        <td><%= attendance.employee_id %></td>
        <td><%= link_to 'Show', attendance %></td>
        <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance', new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check in:</strong>
  <%= @attendance.check_in %>
</p>

<p>
  <strong>Check out:</strong>
  <%= @attendance.check_out %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @attendance.employee_id %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

app/views/employees/_form.html.erb
<%= form_with(model: employee, class: "form-group") do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :store %>
    <%= form.select :store_id, stores_for_select, {}, class: "form-select" %>
  </div>
  
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :position %>
    <%= form.text_field :position, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :private_number %>
    <%= form.text_field :private_number, class: "form-control"  %>
  </div>

  <div class="form-group">
    <div class="form-check">
      <%= form.check_box :active, class: "form-check-input" %>
      <%= form.label :active %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
    
  </div>
<% end %>

app/views/employees/index.html.erb
<div class="container table-container">
<p id="notice"><%= notice %></p>

<h1>Employees</h1>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th scope="col">id#</th>
        <th scope="col">Email</th>
        <th scope="col">Name</th>
        <th scope="col">Position</th>
        <th scope="col">Private number</th>
        <th scope="col">Store</th>
        <th scope="col">Active</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.id %></td>
          <td><%= employee.email %></td>
          <td><%= employee.name %></td>
          <td><%= employee.position %></td>
          <td><%= employee.private_number %></td>
          <td><%= employee.store.name %></td>
          <td><%= (employee.active)? "Active": "Inactive" %></td>
          <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editModal<%= employee.id %>">
            Edit
          </button></td>
          <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#showModal<%= employee.id %>">
            show
          </button></td>
        </tr>
        <div class="modal fade" id="editModal<%= employee.id %>" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Employee</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
              <p id="notice"><%= notice %></p>

                <%= render 'form', employee: employee %>
              </div>
              <div class= "modal-footer">
                <%= link_to 'Show', employee, class: "btn btn-secondary" %>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="showModal<%= employee.id %>" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Employee <%= employee.name %></h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                 <p id="notice"><%= notice %></p>

                    <p>
                      <strong>Email:</strong>
                      <%= employee.email %>
                    </p>

                    <p>
                      <strong>Name:</strong>
                      <%= employee.name %>
                    </p>

                    <p>
                      <strong>Position:</strong>
                      <%= employee.position %>
                    </p>

                    <p>
                      <strong>Private number:</strong>
                      <%= employee.private_number %>
                    </p>

                    <p>
                      <strong>Active:</strong>
                      <%= employee.active %>
                    </p>

                    <p>
                      <strong>Id:</strong>
                      <%= employee.id %>
                    </p>
              </div>
              <div class= "modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </tbody>
  </table>
<br>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newModal">
  New Employee
</button>
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Employee</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <p id="notice"><%= notice %></p>

        <%= render 'form', employee: Employee.new%>
      </div>
      <div class= "modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kata07RelojChecadorAug21K07T02</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous">
    </script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar'%>
    <%= render 'partials/flash_messages'%>
    <%= yield %>
  </body>
</html>

app/views/partials/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, msg, class: "alert alert-#{type}" %>
<% end %>

app/views/partials/_navbar.html.erb
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Just in time!</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/admin/new">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Managment
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/employees">View Employees</a></li>
                <li><a class="dropdown-item" href="/employees/new">Create Employee</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="/stores">View Stores</a></li>
                <li><a class="dropdown-item" href="/stores/new">Create Store</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Report", attendances_path, class: "dropdown-item" %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= button_to  "Log out", admin_path(1), method: :delete, class: "btn btn-danger" %> 

app/views/stores/_form.html.erb
<%= form_with(model: store) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<div class="container table-container">
  <p id="notice"><%= notice %></p>

  <h1>Stores</h1>

  <table class="table table-hover table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @stores.each do |store| %>
        <tr>
          <td><%= store.name %></td>
          <td><%= store.address %></td>
          <td><%= link_to image_tag("find.png", size: "40x40"), store %></td>
          <td><%= link_to image_tag("edit.png", size: "40x40"), edit_store_path(store) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Store', new_store_path, class: "btn btn-success " %>
</div>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>

app/views/welcome/index.html.erb
<div class="checkin-background">
  <div class="container text-center checkin-form">
    <div id="MyClockDisplay" class="clock" onload="showTime()"> </div>
    <%= javascript_pack_tag 'index', 'data-turbolinks-track': 'reload' %>

    <%= form_tag 'attendances', id: 'change_path' do%>
    <%= text_field_tag :private_number %>
    <%= submit_tag "Check in", id: 'check_in' %>
    <%= submit_tag "Check out", formmethod: "patch", id: 'check_out' %>
    <% end %>






    <%= form_with(model: Attendance.first, id: 'change_path') do |form| %>
    <div class="container checkin-buttons-container">
      <div class="field">
        <%= form.label :private_number %><br>
        <%= form.text_field :private_number, class: "container private-number-input" %><br>
      </div>

      <div class="actions">
        <%= form.submit 'check_in', id: 'check_ins', class: "btn btn-success check-button" %>
      </div>

      <div class="actions">
        <%= form.submit 'check_out', id: 'check_outs', class: "btn btn-danger check-button" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<script>
  const change_path = document.getElementById('change_path')
  const check_in = document.getElementById('check_out')

  check_out.addEventListener("click", employee_check_out)
  console.log(change_path.action)

  function employee_check_out() {
    change_path.action = 'PATCH patch'
    change_path.action = '/attendances/'
  }
</script>